version: "3.7"
services:
  atm_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
    volumes:
      - ./logs:/logs
  mongo_db:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017